### PR TITLE
Generate Schedule JSON

### PR DESCRIPTION
**Pull request by kyleyarwood**

### CODE REVIEW

**Comment by RamVasuthevan** [comment]
The script currently fails as folder output does not exist

**Comment by RamVasuthevan** [comment]
run isort on json_schedule_generator?

**Comment by RamVasuthevan** [comment]
Log formatting: I perfer something like [this](https://github.com/RamVasuthevan/ontario-legislature-bills/blob/main/src/log_config.py#L6), but it's your choice

**Comment by kyleyarwood** [comment]
> The script currently fails as folder output does not exist

This should pass when merged into main since there is an output folder, assuming it's run from the right path in the GH action

**Review by RamVasuthevan — APPROVED** [review]

**Pull request merged**
