### PR TITLE
Create generate-schedule-json job

### PR DESCRIPTION
**Pull request by kyleyarwood**

### CODE REVIEW

**Review by RamVasuthevan — COMMENTED** [review]
Looks good:

- If you run it on this branch, I expect it to either make a commit to this branch or fail because it doesn't have permissions. 
- Do you want to allow it to commit directly or for it to make a PR?
- Also, can we have it run daily? I don't know how in advance they post new schedules the

**Comment by kyleyarwood** [comment]
> Looks good:
> 
>     * If you run it on this branch, I expect it to either make a commit to this branch or fail because it doesn't have permissions.
> 
>     * Do you want to allow it to commit directly or for it to make a PR?
> 
>     * Also, can we have it run daily? I don't know how in advance they post new schedules the

@RamVasuthevan 
* I know it can generate the file and check if it should push. Any opinions on testing it on main? Also do we want it to commit to the branch it's run on?
* How sacred is branch protection to you?
* Yes, I can change it to run daily

**Comment by RamVasuthevan** [comment]
1. I have no problems with testing on main now. But I think it's nice if it pushes to the branch it's run on. It makes testing in the future easier 
2. Branch protection is not sacred at all to me. I'm just afraid that the website structure will change, and an incorrect schedule will get pushed to main

**Comment by RamVasuthevan** [comment]
[Here](https://github.com/RamVasuthevan/whois-server-list/blob/b9bda402ec37d88eebe59bac5972f35b06bc6a33/.github/workflows/whois_update.yml#L47) is an example of an Action which creates a PR

**Review by RamVasuthevan — APPROVED** [review]

**Pull request merged**
